require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AlgorithmBinariesController do

  def mock_algorithm_binary(stubs={})
    @mock_algorithm_binary ||= mock_model(AlgorithmBinary, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all algorithm_binaries as @algorithm_binaries" do
      AlgorithmBinary.stub(:all) { [mock_algorithm_binary] }
      get :index
      assigns(:algorithm_binaries).should eq([mock_algorithm_binary])
    end
  end

  describe "GET show" do
    it "assigns the requested algorithm_binary as @algorithm_binary" do
      AlgorithmBinary.stub(:find).with("37") { mock_algorithm_binary }
      get :show, :id => "37"
      assigns(:algorithm_binary).should be(mock_algorithm_binary)
    end
  end

  describe "GET new" do
    it "assigns a new algorithm_binary as @algorithm_binary" do
      AlgorithmBinary.stub(:new) { mock_algorithm_binary }
      get :new
      assigns(:algorithm_binary).should be(mock_algorithm_binary)
    end
  end

  describe "GET edit" do
    it "assigns the requested algorithm_binary as @algorithm_binary" do
      AlgorithmBinary.stub(:find).with("37") { mock_algorithm_binary }
      get :edit, :id => "37"
      assigns(:algorithm_binary).should be(mock_algorithm_binary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created algorithm_binary as @algorithm_binary" do
        AlgorithmBinary.stub(:new).with({'these' => 'params'}) { mock_algorithm_binary(:save => true) }
        post :create, :algorithm_binary => {'these' => 'params'}
        assigns(:algorithm_binary).should be(mock_algorithm_binary)
      end

      it "redirects to the created algorithm_binary" do
        AlgorithmBinary.stub(:new) { mock_algorithm_binary(:save => true) }
        post :create, :algorithm_binary => {}
        response.should redirect_to(algorithm_binary_url(mock_algorithm_binary))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved algorithm_binary as @algorithm_binary" do
        AlgorithmBinary.stub(:new).with({'these' => 'params'}) { mock_algorithm_binary(:save => false) }
        post :create, :algorithm_binary => {'these' => 'params'}
        assigns(:algorithm_binary).should be(mock_algorithm_binary)
      end

      it "re-renders the 'new' template" do
        AlgorithmBinary.stub(:new) { mock_algorithm_binary(:save => false) }
        post :create, :algorithm_binary => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested algorithm_binary" do
        AlgorithmBinary.stub(:find).with("37") { mock_algorithm_binary }
        mock_algorithm_binary.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :algorithm_binary => {'these' => 'params'}
      end

      it "assigns the requested algorithm_binary as @algorithm_binary" do
        AlgorithmBinary.stub(:find) { mock_algorithm_binary(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:algorithm_binary).should be(mock_algorithm_binary)
      end

      it "redirects to the algorithm_binary" do
        AlgorithmBinary.stub(:find) { mock_algorithm_binary(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(algorithm_binary_url(mock_algorithm_binary))
      end
    end

    describe "with invalid params" do
      it "assigns the algorithm_binary as @algorithm_binary" do
        AlgorithmBinary.stub(:find) { mock_algorithm_binary(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:algorithm_binary).should be(mock_algorithm_binary)
      end

      it "re-renders the 'edit' template" do
        AlgorithmBinary.stub(:find) { mock_algorithm_binary(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested algorithm_binary" do
      AlgorithmBinary.stub(:find).with("37") { mock_algorithm_binary }
      mock_algorithm_binary.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the algorithm_binaries list" do
      AlgorithmBinary.stub(:find) { mock_algorithm_binary }
      delete :destroy, :id => "1"
      response.should redirect_to(algorithm_binaries_url)
    end
  end

end
